### ISSUE TITLE
Ignore instructions/@'ing BHoMBot from within markdown quotes

### ISSUE THREAD

**Issue by al-fisher** [BuroHappoldEngineeringAdmin/BHoMBot-CI#35]
See https://github.com/BuroHappoldEngineering/BuildingEnvironments_Toolkit/pull/305#issuecomment-669993202

Should we look at ignoring any text inside markdown quote block - that is text after "> "?

**Comment by FraserGreenroyd** [comment]
Because of the way we have checks set up from comments, I think yes. It is very easy to do a large comment that includes the keywords which will trigger a check, but quoting that comment shouldn't retrigger the check :smile:
